name: inputter
description: Desktop automation
version: 1.0.1
homepage: https://www.inputter.dev

platforms:
  windows:

repository: https://github.com/simonmdsn/inputter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  image: ^3.2.0
  win32: ^2.7.0
  ffi: '>=1.1.2 <3.0.0'

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
